# See https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/#modstoml
# Placeholders such as mod_id and mod_version are filled in from gradle.properties by the processResources task.

modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/onetruespec/shared_workspace/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# The sorter works with the mod on both sides; a client or server without it may still connect.
displayTest="IGNORE_ALL_VERSION"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
